import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Link from "next/link";
import LoginPage from "./authentication/loginPage";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>nextstack_coba</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      {/* <LandingPageTemplate /> */}
      <LoginPage />
    </>
  );
};

export default Index;
